### ISSUE TITLE
Keep your description short

### ISSUE THREAD

**Issue by andreareginato** [andreareginato/betterspecs#4]
Write your thoughts about the "[keep your description short](http://betterspecs.org/#short)" best practice.

**Comment by mattvanhorn** [comment]
"not valid" conveys a lot less useful information than "has unexpected parameters"
I think it is bad practice to encourage vague specifications.
I shouldn't have to go searching for the subject or setup to find out what "not valid" means.
http://xunitpatterns.com/Obscure%20Test.html#Mystery Guest

**Comment by yudapc** [comment]
Before that is worked. But now It does not work.
`it { is_expected.to respond_with :ok }`
and get error message:
```
NoMethodError:
       undefined method `respond_with' for #<RSpec::ExampleGroups::SitemapsController::GETChords:0x007fd8aeb5cf78>
```

So for quick fix I changed to:
`it { expect(response).to have_http_status(200) }`

anyone have good solution for that?

**Comment by yudapc** [comment]
I'm sorry, This error because `gem 'shoulda-matchers'`
The solution I changed `gem 'shoulda-matchers'` to `gem 'shoulda', '~> 3.5'`

**Comment by jmonsanto** [comment]
IMHO, 40 characters is really limiting -- may even result to much more confusion for the sake of meeting the 40 char limit. Conciseness is key though.

It's better if rephrased like this:

> A spec description *ideally* should never be longer than 40 characters. If this happens you should split it using a context.

**Comment by aesyondu** [comment]
I've read the first three best practices now (describe, context, description length), and in 2/3, I agree to the counter arguments in the discussion:

https://github.com/betterspecs/betterspecs/issues/2#issuecomment-9106542
https://github.com/betterspecs/betterspecs/issues/4#issuecomment-9113619

Maybe I'm just missing something, it could possibly be because of my lack of experience.

**Comment by ChaelCodes** [comment]
I think the example context here is vague and unhelpful compared to the original description. I like the 40 characters guideline, but the example is weak.
```
context 'when not valid' do
  it { is_expected.to respond_with 422 }
end
```

I think it'd be better to recommend a clear context:
```
context 'with unexpected params' do
  it { is_expected.to respond_with 422 }
end
```

**Comment by akz92** [comment]
I agree @ChaelCodes, your suggestion is much more descriptive of the actual context

**Comment by lortza** [comment]
I also agree with @ChaelCodes because I prefer specificity and try to write code in a dont-make-future-me-have-to-think-too-hard-about-this kind of way. 

Along those lines, I could argue that some well-named variables could reduce more cognitive overhead when reading the various expected values that don't have obvious meaning (such as http response status codes from these examples). This allows us to keep our descriptions concise while also making each `it` statement easier to instantly understand. 

```ruby
# I hoisted these because I'm pretending that there are more scenarios 
let(:unauthorized) { 401 }
let(:unprocessable_content) { 422 }

context 'when logged out' do
  it { is_expected.to respond_with unauthorized }
end

context 'with unexpected params' do
  it { is_expected.to respond_with unprocessable_content }
end
```

This is a small side-step from the conversation directly about context copy, but still covers ways in which organic documentation can make code easier to read -- and I haven't seen that elsewhere in the docs.
